name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: node:alpine:3.14
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
